spring:
  datasource:
    url: jdbc:oracle:thin:@${ORACLE_URL}:1521:${ORACLE_SID}
    username: ${ORACLE_USER}
    password: ${ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  data:
    mongodb:
      uri: ${MONGO_HOST}
      database: ${MONGO_DATABASE}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.Oracle10gDialect
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB-CLIENT-ID}
            client-secret: ${GITHUB-CLIENT-SECRET}
            scope: read:user,user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  thymeleaf:
    encoding: UTF-8
    mode: HTML
    cache: false
